# Generated by Django 3.2.9 on 2021-11-12 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('email_address', models.EmailField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_api.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('REGULAR', 'Regular'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], max_length=20)),
                ('order_status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('PRODUCTION', 'In production'), ('DELIVERING', 'Left to Deliver'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=15)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_api.customer')),
                ('customer_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_api.customeraddress')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_api.pizza')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', '-id'], name='pizza_api_o_custome_5fd88f_idx'),
        ),
    ]
