# Generated by Django 3.2.9 on 2021-11-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
